// Comprehensive country and city data
export const countriesWithCities = {
  US: {
    name: "United States",
    flag: "🇺🇸",
    cities: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San Jose",
      "Austin",
      "Jacksonville",
      "Fort Worth",
      "Columbus",
      "Charlotte",
      "San Francisco",
      "Indianapolis",
      "Seattle",
      "Denver",
      "Washington",
      "Boston",
      "El Paso",
      "Nashville",
      "Detroit",
      "Oklahoma City",
      "Portland",
      "Las Vegas",
      "Memphis",
      "Louisville",
      "Baltimore",
      "Milwaukee",
      "Albuquerque",
      "Tucson",
      "Fresno",
      "Sacramento",
      "Kansas City",
      "Mesa",
      "Atlanta",
      "Omaha",
      "Colorado Springs",
      "Raleigh",
      "Miami",
      "Oakland",
      "Minneapolis",
      "Tulsa",
      "Cleveland",
      "Wichita",
      "Arlington",
    ],
  },
  GB: {
    name: "United Kingdom",
    flag: "🇬🇧",
    cities: [
      "London",
      "Birmingham",
      "Manchester",
      "Glasgow",
      "Liverpool",
      "Leeds",
      "Sheffield",
      "Edinburgh",
      "Bristol",
      "Cardiff",
      "Leicester",
      "Belfast",
      "Nottingham",
      "Newcastle",
      "Brighton",
      "Hull",
      "Plymouth",
      "Stoke-on-Trent",
      "Wolverhampton",
      "Derby",
      "Swansea",
      "Southampton",
      "Salford",
      "Aberdeen",
      "Westminster",
      "Portsmouth",
      "York",
      "Peterborough",
      "Dundee",
      "Lancaster",
      "Oxford",
      "Newport",
      "Preston",
      "St Albans",
      "Norwich",
      "Chester",
      "Cambridge",
      "Salisbury",
      "Exeter",
      "Gloucester",
      "Lisburn",
      "Chichester",
    ],
  },
  CA: {
    name: "Canada",
    flag: "🇨🇦",
    cities: [
      "Toronto",
      "Montreal",
      "Vancouver",
      "Calgary",
      "Edmonton",
      "Ottawa",
      "Winnipeg",
      "Quebec City",
      "Hamilton",
      "Kitchener",
      "London",
      "Victoria",
      "Halifax",
      "Oshawa",
      "Windsor",
      "Saskatoon",
      "St. Catharines",
      "Regina",
      "Sherbrooke",
      "Barrie",
      "Kelowna",
      "Abbotsford",
      "Kingston",
      "Sudbury",
      "Saguenay",
      "Trois-Rivières",
      "Guelph",
      "Cambridge",
      "Whitby",
      "Coquitlam",
      "Saanich",
      "Burlington",
      "Richmond",
      "Oakville",
      "Burnaby",
      "Richmond Hill",
      "Thunder Bay",
      "St. John's",
      "Brantford",
      "Saint-Jean-sur-Richelieu",
    ],
  },
  DE: {
    name: "Germany",
    flag: "🇩🇪",
    cities: [
      "Berlin",
      "Hamburg",
      "Munich",
      "Cologne",
      "Frankfurt",
      "Stuttgart",
      "Düsseldorf",
      "Dortmund",
      "Essen",
      "Leipzig",
      "Bremen",
      "Dresden",
      "Hanover",
      "Nuremberg",
      "Duisburg",
      "Bochum",
      "Wuppertal",
      "Bielefeld",
      "Bonn",
      "Münster",
      "Karlsruhe",
      "Mannheim",
      "Augsburg",
      "Wiesbaden",
      "Gelsenkirchen",
      "Mönchengladbach",
      "Braunschweig",
      "Chemnitz",
      "Kiel",
      "Aachen",
      "Halle",
      "Magdeburg",
      "Freiburg",
      "Krefeld",
      "Lübeck",
      "Oberhausen",
      "Erfurt",
      "Mainz",
      "Rostock",
      "Kassel",
      "Hagen",
      "Potsdam",
    ],
  },
  FR: {
    name: "France",
    flag: "🇫🇷",
    cities: [
      "Paris",
      "Marseille",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Strasbourg",
      "Montpellier",
      "Bordeaux",
      "Lille",
      "Rennes",
      "Reims",
      "Le Havre",
      "Saint-Étienne",
      "Toulon",
      "Angers",
      "Grenoble",
      "Dijon",
      "Nîmes",
      "Aix-en-Provence",
      "Saint-Quentin-en-Yvelines",
      "Brest",
      "Le Mans",
      "Amiens",
      "Tours",
      "Limoges",
      "Clermont-Ferrand",
      "Villeurbanne",
      "Besançon",
      "Orléans",
      "Metz",
      "Rouen",
      "Mulhouse",
      "Perpignan",
      "Caen",
      "Boulogne-Billancourt",
      "Nancy",
      "Fort-de-France",
      "Roubaix",
      "Tourcoing",
      "Nanterre",
      "Avignon",
    ],
  },
  JP: {
    name: "Japan",
    flag: "🇯🇵",
    cities: [
      "Tokyo",
      "Yokohama",
      "Osaka",
      "Nagoya",
      "Sapporo",
      "Fukuoka",
      "Kobe",
      "Kawasaki",
      "Kyoto",
      "Saitama",
      "Hiroshima",
      "Sendai",
      "Kitakyushu",
      "Chiba",
      "Sakai",
      "Niigata",
      "Hamamatsu",
      "Okayama",
      "Sagamihara",
      "Kumamoto",
      "Shizuoka",
      "Kagoshima",
      "Matsuyama",
      "Kanazawa",
      "Utsunomiya",
      "Matsudo",
      "Kawaguchi",
      "Ichikawa",
      "Fujisawa",
      "Hachioji",
      "Nishinomiya",
      "Kurashiki",
      "Fukuyama",
      "Toyonaka",
      "Toyohashi",
      "Nara",
      "Nagasaki",
      "Machida",
      "Gifu",
      "Hirakata",
      "Fujisawa",
      "Kashiwa",
    ],
  },
  AU: {
    name: "Australia",
    flag: "🇦🇺",
    cities: [
      "Sydney",
      "Melbourne",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Gold Coast",
      "Newcastle",
      "Canberra",
      "Sunshine Coast",
      "Wollongong",
      "Hobart",
      "Geelong",
      "Townsville",
      "Cairns",
      "Darwin",
      "Toowoomba",
      "Ballarat",
      "Bendigo",
      "Albury",
      "Launceston",
      "Mackay",
      "Rockhampton",
      "Bunbury",
      "Bundaberg",
      "Coffs Harbour",
      "Wagga Wagga",
      "Hervey Bay",
      "Mildura",
      "Shepparton",
      "Port Macquarie",
      "Gladstone",
      "Tamworth",
      "Traralgon",
      "Orange",
      "Bowral",
      "Geraldton",
      "Dubbo",
      "Nowra",
      "Warrnambool",
    ],
  },
  IN: {
    name: "India",
    flag: "🇮🇳",
    cities: [
      "Mumbai",
      "Delhi",
      "Bangalore",
      "Hyderabad",
      "Ahmedabad",
      "Chennai",
      "Kolkata",
      "Surat",
      "Pune",
      "Jaipur",
      "Lucknow",
      "Kanpur",
      "Nagpur",
      "Indore",
      "Thane",
      "Bhopal",
      "Visakhapatnam",
      "Pimpri-Chinchwad",
      "Patna",
      "Vadodara",
      "Ghaziabad",
      "Ludhiana",
      "Agra",
      "Nashik",
      "Faridabad",
      "Meerut",
      "Rajkot",
      "Kalyan-Dombivali",
      "Vasai-Virar",
      "Varanasi",
      "Srinagar",
      "Dhanbad",
      "Jodhpur",
      "Amritsar",
      "Raipur",
      "Allahabad",
      "Coimbatore",
      "Jabalpur",
      "Gwalior",
      "Vijayawada",
      "Madurai",
      "Guwahati",
    ],
  },
  BR: {
    name: "Brazil",
    flag: "🇧🇷",
    cities: [
      "São Paulo",
      "Rio de Janeiro",
      "Brasília",
      "Salvador",
      "Fortaleza",
      "Belo Horizonte",
      "Manaus",
      "Curitiba",
      "Recife",
      "Goiânia",
      "Belém",
      "Porto Alegre",
      "Guarulhos",
      "Campinas",
      "São Luís",
      "São Gonçalo",
      "Maceió",
      "Duque de Caxias",
      "Nova Iguaçu",
      "Teresina",
      "Natal",
      "Campo Grande",
      "São Bernardo do Campo",
      "João Pessoa",
      "Santo André",
      "Osasco",
      "Jaboatão dos Guararapes",
      "Contagem",
      "São José dos Campos",
      "Uberlândia",
      "Sorocaba",
      "Cuiabá",
      "Aparecida de Goiânia",
      "Aracaju",
      "Feira de Santana",
      "Londrina",
      "Juiz de Fora",
      "Belford Roxo",
    ],
  },
  SG: {
    name: "Singapore",
    flag: "🇸🇬",
    cities: [
      "Singapore",
      "Jurong East",
      "Woodlands",
      "Tampines",
      "Sengkang",
      "Hougang",
      "Yishun",
      "Bedok",
      "Punggol",
      "Ang Mo Kio",
      "Toa Payoh",
      "Pasir Ris",
      "Clementi",
      "Choa Chu Kang",
      "Bukit Batok",
      "Bishan",
      "Serangoon",
      "Bukit Merah",
      "Geylang",
      "Kallang",
      "Queenstown",
      "Marine Parade",
      "Central Water Catchment",
      "Bukit Timah",
      "Novena",
      "Orchard",
      "River Valley",
    ],
  },
}

export const countries = Object.entries(countriesWithCities).map(([code, data]) => ({
  code,
  name: data.name,
  flag: data.flag,
}))

export const getCitiesForCountry = (countryCode: string): string[] => {
  return countriesWithCities[countryCode as keyof typeof countriesWithCities]?.cities || []
}
