# /.github/workflows/docker-build.yml
name: 🚀 Build & Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ensures full context is available

      # Step 2: Set up Docker Buildx (recommended for GHCR)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/vynox-admin:latest
            ghcr.io/${{ secrets.GHCR_USERNAME }}/vynox-admin:${{ github.sha }}
